import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import Header from "@/components/sb/Header";
import Footer from "@/components/sb/Footer";
import { getStoryblokApi } from "@/lib/storyblok";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // hämta global story
  const storyblokApi = getStoryblokApi();
  const { data } = await storyblokApi.get("cdn/stories/global", {
    version: "draft",
  });

  // header-blok = första objektet i arrayen
  const headerBlok = data.story.content.header?.[0];
  const footerBlok = data.story.content.footer?.[0];

  return (
    <StoryBlokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {headerBlok && <Header blok={headerBlok} />}
          <main>{children}</main>
          {footerBlok && <Footer blok={footerBlok} />}
        </body>
      </html>
    </StoryBlokProvider>
  );
}
